# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Pages/Jekyll.gitlab-ci.yml

# Template project: https://gitlab.com/pages/jekyll
# Docs: https://docs.gitlab.com/ee/pages/
image: ruby:3.2

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8

before_script:
- apt-get update -qq && apt-get install -y -qq curl gnupg
  # Current version of nodejs on ruby:3.2 is too old
  #- curl -sL https://deb.nodesource.com/setup_16.x | bash -
  #- apt-get install -y -qq nodejs
  #- npm install -g npm@latest
  #- npm install imagemin imagemin-jpegtran imagemin-pngquant imagemin-webp imagemin-gifsicle imagemin-svgo sharp
  # Images optimizations
  #- node scripts/optimize-images.js
  # Install Ruby and Jekyll
  - ruby -v
  - gem install bundler
  - bundle install

test:
  stage: test
  script:
    - bundle exec jekyll build -d test
  artifacts:
    paths:
      - test
  rules:
      - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH

pages:
  stage: deploy
  script:
    - bundle exec jekyll build -d public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
